# Generated by Django 5.0.4 on 2025-02-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_create', 'Can create a books'), ('can_view', 'Can view books'), ('can_edit', 'can edit books'), ('can_delete', 'Can delete books'))},
        ),
    ]
